# Generated by Django 5.2.6 on 2026-03-26 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('token', models.CharField(max_length=255, verbose_name='Токен')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активность')),
                ('min_deposit', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Минимальный депозит ($)')),
                ('pixel_id', models.CharField(blank=True, default='', max_length=100, verbose_name='Facebook Pixel ID')),
                ('pixel_token', models.CharField(blank=True, default='', max_length=500, verbose_name='Facebook Pixel API Token')),
            ],
            options={
                'verbose_name': 'Бот',
                'verbose_name_plural': 'Боты',
            },
        ),
        migrations.CreateModel(
            name='BotMarketing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст рассылки')),
                ('image', models.ImageField(blank=True, upload_to='telegram_images/', verbose_name='Изображение')),
                ('segment', models.CharField(choices=[('all', 'Все пользователи'), ('no_access', 'Без доступа'), ('test', 'Тестовый доступ'), ('full', 'Полный доступ')], default='all', max_length=20, verbose_name='Сегмент аудитории')),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.bot')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('method', models.CharField(max_length=100, verbose_name='Кодовое имя')),
                ('channel_id', models.CharField(blank=True, max_length=100, verbose_name='ID канала')),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.bot')),
            ],
            options={
                'verbose_name': 'Канал',
                'verbose_name_plural': 'Каналы',
            },
        ),
        migrations.CreateModel(
            name='CustomSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=100, verbose_name='ID телеграмма')),
                ('text', models.TextField(verbose_name='Текст сообщения')),
                ('direction', models.CharField(choices=[('higher', 'Higher'), ('lower', 'Lower')], default='higher', max_length=100, verbose_name='Направление сигнала')),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.bot')),
            ],
            options={
                'verbose_name': 'Кастомный сигнал',
                'verbose_name_plural': 'Кастомные сигналы',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('image', models.ImageField(upload_to='telegram_images/', verbose_name='Изображение')),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.bot')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('method', models.CharField(max_length=100, verbose_name='Кодовое имя')),
                ('url', models.URLField(max_length=500, verbose_name='Ссылка')),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.bot')),
            ],
            options={
                'verbose_name': 'Ссылка',
                'verbose_name_plural': 'Ссылки',
            },
        ),
        migrations.CreateModel(
            name='MultiChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(max_length=100, verbose_name='ID супергруппы')),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.bot')),
            ],
            options={
                'verbose_name': 'Мультичат',
                'verbose_name_plural': 'Мультичаты',
            },
        ),
        migrations.CreateModel(
            name='BotAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=100, verbose_name='ID телеграмма')),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.bot')),
            ],
            options={
                'verbose_name': 'Полный доступ',
                'verbose_name_plural': 'Полные доступы',
                'unique_together': {('bot', 'chat_id')},
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=100, verbose_name='Кодовое имя')),
                ('language', models.CharField(choices=[('en', 'English 🇬🇧'), ('es', 'Español 🇪🇸'), ('pt', 'Português 🇵🇹')], default='en', max_length=10, verbose_name='Язык')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст сообщения')),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.bot')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='bot.image', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'unique_together': {('bot', 'method', 'language')},
            },
        ),
        migrations.CreateModel(
            name='Postback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(blank=True, default='', max_length=100, verbose_name='ID телеграмма')),
                ('user_id', models.CharField(max_length=100, verbose_name='ID пользователя на платформе')),
                ('link_id', models.CharField(max_length=100, verbose_name='ID реферальной ссылки')),
                ('deposit', models.BooleanField(default=False, verbose_name='Депозит совершён')),
                ('deposit_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Сумма депозита ($)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('deposited_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата депозита')),
                ('bot', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.bot')),
            ],
            options={
                'verbose_name': 'Постбэк',
                'verbose_name_plural': 'Постбэки',
                'unique_together': {('user_id', 'link_id')},
            },
        ),
        migrations.CreateModel(
            name='TempAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=100, verbose_name='ID телеграмма')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.bot')),
            ],
            options={
                'verbose_name': 'Тестовый доступ',
                'verbose_name_plural': 'Тестовые доступы',
                'unique_together': {('bot', 'chat_id')},
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=100, verbose_name='ID телеграмма')),
                ('topic_id', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='ID топика')),
                ('language', models.CharField(choices=[('en', 'English 🇬🇧'), ('es', 'Español 🇪🇸'), ('pt', 'Português 🇵🇹')], default='en', max_length=10, verbose_name='Язык')),
                ('username', models.CharField(blank=True, default='', max_length=100, verbose_name='Username')),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.bot')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'unique_together': {('bot', 'chat_id')},
            },
        ),
    ]
